name: npm test
on:
  workflow_dispatch:
               
jobs:
  install-node:               # Name of the job 1
    runs-on: ubuntu-latest
    steps:
      - name: install node
        run: npm install
      - name: amener le code vers les VM suivantes
        uses: actions/checkout@v3
  setup-node:               # Name of the job 1
    needs: install-node
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: configurer les modules de node
        run: npm ci
      - name: tester node
        run: npm test
      - name: retourner l'état du repo vers les VM suivantes
        uses: actions/checkout@v3
