name: Switch Node version
on: 
  pull_request:

# env:
#   NODE_VERSION: 14

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Recupérer mes sources et notamment la source Node
        uses: actions/checkout@v3
      - name: Set the value
        id: step_one
        run: |
          echo "NODE_VERSION=14" >> $GITHUB_ENV

      - name : setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE_VERSION  }}"
      - name: run test
        shell: bash
        run: |
          npm install
          npm test
          node -v

