name: reusable workflow
on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: $NODE_VERSION
        - name: run test
          shell: bash
          run: |
            node -v
            npm install
            npm test
