name: Ex6-cache
on: 
  workflow_dispatch:

jobs:
  run-npm-install:
    runs-on: ubuntu-latest
    steps:
        - name: Cache node modules
          uses: actions/cache@v3
          env:
            cache-name: cache-node-modules-v4
          with:
            # node_modules cache files are stored in `~/node_modules` on Linux/macOS
            path: node_modules
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('*/package-lock.json') }}

        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: 'lts/*'
        - name: run install
          shell: bash
          run: |
            npm install

  run-npm-test:
    runs-on: ubuntu-latest
    needs: run-npm-install
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Cache node modules
          uses: actions/cache@v3    
          env:
            cache-name: cache-node-modules-v4
          with:
            # node_modules cache files are stored in `~/node_modules` on Linux/macOS
            path: node_modules
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('*/package-lock.json') }}

        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: 'lts/*'
        - name: run test
          shell: bash
          run: |
            npm test
